name: Build and Auto Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          architecture: x86

      - run: npm install
      - run: npm run build
      - run: npx electron-builder --win --ia32

      - name: Delete old release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest-build
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build
          name: "Bản Build Tự Động Mới Nhất"
          body: "Bản cài đặt này được máy chủ tự động build mỗi khi có code mới."
          files: dist/*.exe
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
